@extends('layouts.app')

@section('title', 'Trung tâm quản trị')

@push('styles')
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@500;600;700&family=Fira+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
    .admin-console { --ink:#f8fafc; --muted:#94a3b8; --panel:#1b2336; --line:rgba(148,163,184,.22); font-family:'Fira Sans',sans-serif; color:var(--ink); }
    .admin-console h1,.admin-console h2,.metric-value { font-family:'Fira Code',monospace; }
    .admin-shell { background:radial-gradient(circle at 6% 0%,#263c4c 0,transparent 30rem),linear-gradient(135deg,#0f172a,#172033 50%,#0f172a); }
    .admin-panel { background:rgba(27,35,54,.88); border:1px solid var(--line); box-shadow:0 18px 45px rgba(2,6,23,.2); backdrop-filter:blur(12px); }
    .admin-link { transition:background-color .18s ease,border-color .18s ease,transform .18s ease; }
    .admin-link:hover { background:rgba(74,222,128,.09); border-color:rgba(74,222,128,.45); transform:translateY(-2px); }
    .admin-link:focus-visible,.admin-console a:focus-visible { outline:3px solid #f8fafc; outline-offset:3px; }
    .metric-card { min-height:154px; }.metric-card::before { content:'';position:absolute;inset:0 auto 0 0;width:4px;background:var(--accent,#4ade80);border-radius:1rem 0 0 1rem; }
    @media (prefers-reduced-motion:reduce) {.admin-link {transition:none}.admin-link:hover {transform:none}}
</style>
@endpush

@section('content')
<div class="admin-shell admin-console min-h-screen"><div class="max-w-7xl mx-auto px-4 sm:px-6 py-7 sm:py-10">
    <header class="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-6 mb-8">
        <div><p class="uppercase tracking-[.18em] text-xs font-semibold text-emerald-300">Trung tâm điều hành</p><h1 class="text-2xl sm:text-3xl font-bold mt-2">Xin chào, {{ auth()->user()->name }}</h1><p class="text-slate-300 mt-2 max-w-2xl">Theo dõi hệ thống, xử lý nội dung cần duyệt và điều phối sàn nông sản từ một nơi.</p></div>
        <nav aria-label="Điều hướng quản trị" class="grid grid-cols-2 sm:flex gap-2"><a class="admin-link rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold text-center" href="{{ route('admin.users.index') }}">Tài khoản</a><a class="admin-link rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold text-center" href="{{ route('admin.products.index') }}">Sản phẩm</a><a class="admin-link rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold text-center" href="{{ route('admin.certificates.index') }}">Chứng nhận</a><a class="admin-link rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold text-center" href="{{ route('admin.reviews.index') }}">Đánh giá</a></nav>
    </header>

    <section aria-label="Chỉ số tổng quan" class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
        <a href="{{ route('admin.users.index') }}" class="admin-panel admin-link metric-card relative rounded-2xl p-5" style="--accent:#60a5fa"><p class="text-sm text-slate-300">Tài khoản</p><p class="metric-value text-3xl font-bold mt-5">{{ number_format($statistics['users']) }}</p><p class="text-xs text-slate-400 mt-2">{{ number_format($statistics['sellers']) }} người bán đang hoạt động</p></a>
        <a href="{{ route('admin.products.index') }}" class="admin-panel admin-link metric-card relative rounded-2xl p-5" style="--accent:#4ade80"><p class="text-sm text-slate-300">Sản phẩm hiển thị</p><p class="metric-value text-3xl font-bold mt-5">{{ number_format($statistics['active_products']) }}</p><p class="text-xs text-slate-400 mt-2">trên {{ number_format($statistics['products']) }} sản phẩm</p></a>
        <a href="{{ route('admin.certificates.index') }}" class="admin-panel admin-link metric-card relative rounded-2xl p-5" style="--accent:#fbbf24"><p class="text-sm text-slate-300">Chứng nhận chờ duyệt</p><p class="metric-value text-3xl font-bold mt-5">{{ number_format($statistics['pending_certificates']) }}</p><p class="text-xs text-amber-200 mt-2">Cần xử lý để công khai truy xuất</p></a>
        <a href="{{ route('admin.reviews.index') }}" class="admin-panel admin-link metric-card relative rounded-2xl p-5" style="--accent:#c084fc"><p class="text-sm text-slate-300">Đánh giá cần xem</p><p class="metric-value text-3xl font-bold mt-5">{{ number_format($statistics['pending_reviews']) }}</p><p class="text-xs text-slate-400 mt-2">Phản hồi mới từ khách hàng</p></a>
    </section>

    <section class="grid grid-cols-1 xl:grid-cols-3 gap-5 mt-5">
        <div class="admin-panel rounded-2xl p-5 xl:col-span-2"><div class="flex items-start justify-between gap-4 mb-5"><div><h2 class="text-lg font-bold">Hàng đợi cần xử lý</h2><p class="text-sm text-slate-400 mt-1">Ưu tiên chứng nhận để thông tin truy xuất được công khai.</p></div><a class="text-sm font-semibold text-emerald-300 hover:text-emerald-200" href="{{ route('admin.certificates.index') }}">Xem tất cả <span aria-hidden="true">→</span></a></div><div class="divide-y divide-slate-700/70">@forelse($certificates as $certificate)<article class="py-4 first:pt-0 flex flex-col sm:flex-row sm:items-center gap-3"><div class="flex-1 min-w-0"><p class="font-semibold truncate">{{ $certificate->name }}</p><p class="text-sm text-slate-400 mt-1 truncate">{{ $certificate->batch->product->name }} · lô {{ $certificate->batch->batch_code }}</p></div><span class="inline-flex w-fit rounded-full bg-amber-300/15 border border-amber-200/20 px-2.5 py-1 text-xs font-semibold text-amber-200">Chờ duyệt</span><a class="admin-link text-center rounded-lg border border-emerald-300/40 px-3 py-2 text-sm font-semibold text-emerald-200" href="{{ route('admin.certificates.index') }}">Xử lý</a></article>@empty<div class="py-9 text-center"><p class="font-semibold">Hàng đợi trống</p><p class="text-sm text-slate-400 mt-1">Không có chứng nhận đang chờ duyệt.</p></div>@endforelse</div></div>
        <aside class="admin-panel rounded-2xl p-5"><h2 class="text-lg font-bold">Trạng thái chứng nhận</h2><p class="text-sm text-slate-400 mt-1 mb-6">Tổng quan chất lượng hồ sơ</p>@php($certificateTotal = max(1, array_sum($certificateStatus)))<div class="space-y-5">@foreach(['approved'=>['Đã duyệt','bg-emerald-400'],'pending'=>['Chờ duyệt','bg-amber-300'],'rejected'=>['Từ chối','bg-rose-400']] as $key => [$label,$color])<div><div class="flex justify-between text-sm mb-2"><span class="text-slate-300">{{ $label }}</span><span class="font-semibold">{{ $certificateStatus[$key] }}</span></div><div class="h-2 rounded-full bg-slate-700 overflow-hidden"><div class="h-full rounded-full {{ $color }}" style="width:{{ ($certificateStatus[$key] / $certificateTotal) * 100 }}%"></div></div></div>@endforeach</div><a class="admin-link mt-7 flex items-center justify-between rounded-xl border border-slate-600 p-3 text-sm font-semibold" href="{{ route('admin.certificates.index') }}"><span>Quản lý chứng nhận</span><span aria-hidden="true">→</span></a></aside>
    </section>

    <section class="grid grid-cols-1 lg:grid-cols-2 gap-5 mt-5">
        <div class="admin-panel rounded-2xl p-5"><div class="flex justify-between items-center mb-4"><div><h2 class="text-lg font-bold">Sản phẩm mới</h2><p class="text-sm text-slate-400">Kiểm tra danh mục và người bán.</p></div><a class="text-sm font-semibold text-emerald-300 hover:text-emerald-200" href="{{ route('admin.products.index') }}">Mở quản lý</a></div><div class="overflow-x-auto"><table class="w-full min-w-[460px] text-sm"><thead class="text-left text-xs uppercase tracking-wider text-slate-400"><tr><th class="pb-3 font-medium">Sản phẩm</th><th class="pb-3 font-medium">Người bán</th><th class="pb-3 font-medium text-right">Trạng thái</th></tr></thead><tbody class="divide-y divide-slate-700/70">@forelse($recentProducts as $product)<tr><td class="py-3"><p class="font-semibold">{{ $product->name }}</p><p class="text-xs text-slate-400 mt-1">{{ $product->category?->name ?? 'Chưa phân loại' }}</p></td><td class="py-3 text-slate-300">{{ $product->seller?->name ?? '—' }}</td><td class="py-3 text-right"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $product->status ? 'bg-emerald-300/15 text-emerald-200' : 'bg-slate-500/20 text-slate-300' }}">{{ $product->status ? 'Đang hiển thị' : 'Đã ẩn' }}</span></td></tr>@empty<tr><td colspan="3" class="py-8 text-center text-slate-400">Chưa có sản phẩm.</td></tr>@endforelse</tbody></table></div></div>
        <div class="admin-panel rounded-2xl p-5"><div class="flex justify-between items-center mb-4"><div><h2 class="text-lg font-bold">Hoạt động gần đây</h2><p class="text-sm text-slate-400">Tài khoản và đánh giá mới nhất.</p></div><a class="text-sm font-semibold text-emerald-300 hover:text-emerald-200" href="{{ route('admin.users.index') }}">Tài khoản</a></div><div class="space-y-3">@forelse($recentUsers as $user)<div class="flex gap-3 items-center"><div class="shrink-0 h-9 w-9 rounded-full bg-slate-700 text-emerald-200 flex items-center justify-center font-bold" aria-hidden="true">{{ mb_strtoupper(mb_substr($user->name,0,1)) }}</div><div class="min-w-0 flex-1"><p class="font-semibold truncate">{{ $user->name }}</p><p class="text-xs text-slate-400 truncate">{{ $user->email }}</p></div><span class="text-xs capitalize text-slate-300">{{ $user->role }}</span></div>@empty<p class="text-center text-slate-400 py-7">Chưa có hoạt động mới.</p>@endforelse</div>@if($recentReviews->isNotEmpty())<div class="mt-5 pt-4 border-t border-slate-700/70"><p class="text-xs uppercase tracking-wider text-slate-400 mb-3">Đánh giá mới</p>@foreach($recentReviews as $review)<p class="text-sm text-slate-300 truncate"><span class="text-amber-200">{{ $review->rating }}/5</span> · {{ $review->product->name }} — {{ $review->user->name }}</p>@endforeach</div>@endif</div>
    </section>
</div></div>
@endsection
