@extends('layouts.admin')

@section('title', 'Quản lý sản phẩm')

@section('admin-content')
<section class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6"><div><h1 class="text-2xl font-bold">Quản lý sản phẩm</h1><p class="text-slate-300 mt-2">Kiểm soát khả năng hiển thị của sản phẩm trên sàn.</p></div><span class="inline-flex w-fit rounded-full bg-emerald-300/15 border border-emerald-200/20 px-3 py-1.5 text-sm font-semibold text-emerald-100">{{ $products->total() }} sản phẩm</span></section>
<form method="GET" class="admin-panel rounded-2xl p-4 mb-5 grid grid-cols-1 sm:grid-cols-[1fr_180px_auto] gap-3"><div><label class="sr-only" for="product-search">Tìm sản phẩm</label><input class="w-full" id="product-search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Tìm tên, xuất xứ hoặc người bán"></div><div><label class="sr-only" for="product-status-filter">Lọc trạng thái</label><select class="w-full" id="product-status-filter" name="status"><option value="">Mọi trạng thái</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Đang hiển thị</option><option value="hidden" @selected(($filters['status'] ?? '') === 'hidden')>Đã ẩn</option></select></div><button class="admin-action rounded-lg bg-emerald-400 px-4 py-2 text-sm font-bold text-slate-950">Lọc</button></form>
<section class="admin-panel rounded-2xl overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-sm"><thead class="bg-slate-950/35 text-left text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4 font-medium">Sản phẩm</th><th class="px-5 py-4 font-medium">Người bán</th><th class="px-5 py-4 font-medium">Giá & tồn kho</th><th class="px-5 py-4 font-medium">Trạng thái</th><th class="px-5 py-4 font-medium text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-700/70">@forelse($products as $product)<tr class="hover:bg-white/[.025]"><td class="px-5 py-4"><p class="font-semibold">{{ $product->name }}</p><p class="text-xs text-slate-400 mt-1">{{ $product->origin ?? 'Chưa có xuất xứ' }}</p></td><td class="px-5 py-4 text-slate-300">{{ $product->seller?->name ?? 'Chưa gán seller' }}</td><td class="px-5 py-4"><p class="font-semibold">{{ number_format($product->price, 0, ',', '.') }} đ</p><p class="text-xs text-slate-400 mt-1">{{ number_format($product->stock) }} tồn kho</p></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $product->status ? 'bg-emerald-300/15 text-emerald-200' : 'bg-slate-500/20 text-slate-300' }}">{{ $product->status ? 'Đang hiển thị' : 'Đã ẩn' }}</span></td><td class="px-5 py-4 text-right"><form method="POST" action="{{ route('admin.products.toggle', $product) }}">@csrf @method('PATCH')<button class="admin-action rounded-lg px-3 py-2 text-sm font-bold {{ $product->status ? 'border-rose-300/50 text-rose-100' : 'border-emerald-300/50 text-emerald-100' }}">{{ $product->status ? 'Ẩn sản phẩm' : 'Hiển thị lại' }}</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-400">Chưa có sản phẩm nào.</td></tr>@endforelse</tbody></table></div></section><div class="mt-5 text-slate-200">{{ $products->links() }}</div>
@endsection
