@extends('layouts.admin')

@section('title', 'Quản lý tài khoản')

@section('admin-content')
<section class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6">
    <div><h1 class="text-2xl font-bold">Quản lý tài khoản</h1><p class="text-slate-300 mt-2">Cập nhật quyền truy cập cho khách hàng, người bán và quản trị viên.</p></div>
    <span class="inline-flex w-fit rounded-full bg-blue-300/15 border border-blue-200/20 px-3 py-1.5 text-sm font-semibold text-blue-100">{{ $users->total() }} tài khoản</span>
</section>

<form method="GET" class="admin-panel rounded-2xl p-4 mb-5 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-[1fr_170px_170px_auto] gap-3">
    <div><label class="sr-only" for="user-search">Tìm tài khoản</label><input class="w-full" id="user-search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Tìm tên, email hoặc số điện thoại"></div>
    <div><label class="sr-only" for="user-role-filter">Lọc vai trò</label><select class="w-full" id="user-role-filter" name="role"><option value="">Mọi vai trò</option><option value="customer" @selected(($filters['role'] ?? '') === 'customer')>Khách hàng</option><option value="seller" @selected(($filters['role'] ?? '') === 'seller')>Người bán</option><option value="admin" @selected(($filters['role'] ?? '') === 'admin')>Quản trị viên</option></select></div>
    <div><label class="sr-only" for="user-status-filter">Lọc trạng thái</label><select class="w-full" id="user-status-filter" name="status"><option value="">Mọi trạng thái</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Đang hoạt động</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Đã khóa</option></select></div>
    <button class="admin-action rounded-lg bg-emerald-400 px-4 py-2 text-sm font-bold text-slate-950">Lọc</button>
</form>

<section class="admin-panel rounded-2xl overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[840px] text-sm"><thead class="bg-slate-950/35 text-left text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4 font-medium">Tài khoản</th><th class="px-5 py-4 font-medium">Liên hệ</th><th class="px-5 py-4 font-medium">Vai trò</th><th class="px-5 py-4 font-medium">Trạng thái</th><th class="px-5 py-4 font-medium text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-700/70">@forelse($users as $user)<tr class="hover:bg-white/[.025]"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="h-10 w-10 shrink-0 rounded-full bg-slate-700 text-emerald-200 flex items-center justify-center font-bold" aria-hidden="true">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</div><div class="min-w-0"><p class="font-semibold truncate max-w-48">{{ $user->name }}</p><p class="text-xs text-slate-400 mt-1">Tham gia {{ $user->created_at?->format('d/m/Y') }}</p></div></div></td><td class="px-5 py-4 text-slate-300"><p class="break-all">{{ $user->email }}</p><p class="text-xs text-slate-400 mt-1">{{ $user->phone ?? 'Chưa có số điện thoại' }}</p></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ match($user->role) {'admin' => 'bg-violet-300/15 text-violet-200', 'seller' => 'bg-emerald-300/15 text-emerald-200', default => 'bg-blue-300/15 text-blue-100'} }}">{{ match($user->role) {'admin' => 'Quản trị viên', 'seller' => 'Người bán', default => 'Khách hàng'} }}</span></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $user->is_active ? 'bg-emerald-300/15 text-emerald-200' : 'bg-rose-300/15 text-rose-200' }}">{{ $user->is_active ? 'Đang hoạt động' : 'Đã khóa' }}</span></td><td class="px-5 py-4"><div class="flex items-center justify-end gap-2"><form class="flex items-center gap-2" method="POST" action="{{ route('admin.users.role', $user) }}">@csrf @method('PATCH')<label class="sr-only" for="role-{{ $user->id }}">Vai trò của {{ $user->name }}</label><select id="role-{{ $user->id }}" name="role"><option value="customer" @selected($user->role === 'customer')>Khách hàng</option><option value="seller" @selected($user->role === 'seller')>Người bán</option><option value="admin" @selected($user->role === 'admin')>Quản trị viên</option></select><button class="admin-action rounded-lg bg-emerald-400 px-3 py-2 text-sm font-bold text-slate-950">Lưu</button></form><form method="POST" action="{{ route('admin.users.status', $user) }}">@csrf @method('PATCH')<button class="admin-action rounded-lg px-3 py-2 text-sm font-bold {{ $user->is_active ? 'border-rose-300/50 text-rose-100' : 'border-emerald-300/50 text-emerald-100' }}">{{ $user->is_active ? 'Khóa' : 'Mở khóa' }}</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-400">Chưa có tài khoản nào.</td></tr>@endforelse</tbody></table></div></section>
<div class="mt-5 text-slate-200">{{ $users->links() }}</div>
@endsection
