<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ isset($product) ? 'Sửa' : 'Thêm' }} sản phẩm</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-slate-50 text-slate-800"><main class="mx-auto max-w-2xl px-4 py-10"><a href="{{ route('seller.products.index') }}" class="text-sm text-emerald-700">← Quay lại danh sách</a><div class="mt-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h1 class="mb-6 text-2xl font-bold">{{ isset($product) ? 'Sửa sản phẩm' : 'Thêm sản phẩm' }}</h1>@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-600">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form method="POST" action="{{ isset($product) ? route('seller.products.update', $product) : route('seller.products.store') }}" class="space-y-4">@csrf @if(isset($product)) @method('PUT') @endif
<label class="block text-sm font-semibold">Tên sản phẩm<input name="name" value="{{ old('name', $product->name ?? '') }}" required class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label class="block text-sm font-semibold">Danh mục<select name="category_id" required class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id ?? '') == $category->id)>Danh mục #{{ $category->id }}</option>@endforeach</select></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold">Giá<input type="number" name="price" min="0" step="0.01" value="{{ old('price', $product->price ?? '') }}" required class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"></label><label class="block text-sm font-semibold">Tồn kho<input type="number" name="stock" min="0" value="{{ old('stock', $product->stock ?? 0) }}" required class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"></label></div>
<label class="block text-sm font-semibold">Nguồn gốc<input name="origin" value="{{ old('origin', $product->origin ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"></label><label class="block text-sm font-semibold">Ảnh sản phẩm (URL)<input type="url" name="image" value="{{ old('image', $product->image ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3"></label><label class="block text-sm font-semibold">Mô tả<textarea name="description" rows="4" class="mt-1 w-full rounded-xl border border-slate-200 px-4 py-3">{{ old('description', $product->description ?? '') }}</textarea></label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="status" value="1" @checked(old('status', $product->status ?? true))> Đang hiển thị sản phẩm</label><button class="w-full rounded-xl bg-[#0e5c36] py-3 font-semibold text-white hover:bg-[#0a4528]">Lưu sản phẩm</button></form></div></main></body></html>
